### Variabelen
@host = http://localhost:4004/odata/v4/event
@contentType = application/json

### Artists

# Alle Artists
GET {{host}}/Artists
Accept: {{contentType}}

### Specifieke Artist
GET {{host}}/Artists(ID='103')
Accept: {{contentType}}

### Maak nieuwe Artist
POST {{host}}/Artists
Content-Type: {{contentType}}

{
  "ID": "108",
  "name": "New Radicals"
}

### Update een Artist
PUT {{host}}/Artists(ID='108')
Content-Type: {{contentType}}

{
  "name": "Old Radicals"
}

### Delete een Artist
DELETE {{host}}/Artists(ID='108')

### Events

### Alle Events
GET {{host}}/Events
Accept: {{contentType}}

### Specifieke Event
GET {{host}}/Events(ID='102')
Accept: {{contentType}}

### Nieuw Event
POST {{host}}/Events
Content-Type: {{contentType}}

{
  "ID": "104",
  "name": "Woodstock 2024",
  "startDate": "2024-01-01",
  "endDate": "2024-01-03",
  "location": "Woodstock"
}


### Stages

# Alle Stages
GET {{host}}/Stages
Accept: {{contentType}}

### Specifieke Stage
GET {{host}}/Stages(ID='103')
Accept: {{contentType}}


### Nieuwe performance
POST http://localhost:4004/flexso/events/Performances
Content-Type: application/json

{
    "ID": "104",
    "startTime": "2024-09-20T18:00:00Z",
    "endTime": "2024-09-20T19:30:00Z",
    "artist_ID": "103",
    "event_ID": "101",
    "stage_ID": "102"
}
